# Generated by Django 4.0 on 2021-12-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idevent', models.AutoField(db_column='idEvent', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=45)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idticket', models.AutoField(db_column='idTicket', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('event_idevent', models.ForeignKey(db_column='Event_idEvent', on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.event')),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.user')),
            ],
            options={
                'db_table': 'ticket',
                'unique_together': {('idticket', 'event_idevent')},
            },
        ),
    ]
