# Generated by Django 4.0 on 2021-12-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_idevent',
            field=models.ForeignKey(db_column='Event_idEvent', on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(max_length=45, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_iduser',
            field=models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=45, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='Фамилия'),
        ),
    ]
