# Generated by Django 4.0 on 2021-12-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_event_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_iduser',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(default='', max_length=45, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='', max_length=45, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='', max_length=45, verbose_name='Фамилия'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
