# Generated by Django 4.0 on 2021-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_user_iduser_ticket_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='Фамилия'),
        ),
    ]
